server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/computersite
        username: root
        password: binge123
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    redis:
        host: 119.29.143.31
        port: 6379
        password: binge123

mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.jking.computersite.entity
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
    level:
        com.jking.computersite.mapper: trace # 改成你的mapper文件所在包路径